Repository Creators-of-Create/Create, pull requests merged in 2024-08, with the labels that each got.

#6769 Add check for Display Link power before gathering data
  src/main/java/com/simibubi/create/content/redstone/displayLink/DisplayLinkBlock.java
Labels: pr type: fix, pr flag: simple

#6389 Added InItemGroup attribute filter
  src/main/java/com/simibubi/create/content/logistics/filter/ItemAttribute.java
Labels: pr type: feature, pr flag: simple

#5940 chore: remove cherry compat recipes
  src/generated/resources/.cache/2d64935085b86659cb7857bad9701dbf9bab6e4c
  src/generated/resources/.cache/b256105d8411632b0d585496ea8944a751a08034
  src/generated/resources/data/create/recipes/cutting/compat/biomesoplenty/cherry_log.json
  src/generated/resources/data/create/recipes/cutting/compat/biomesoplenty/cherry_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/biomesoplenty/stripped_cherry_log.json
  src/generated/resources/data/create/recipes/cutting/compat/biomesoplenty/stripped_cherry_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/blue_skies/cherry_log.json
  src/generated/resources/data/create/recipes/cutting/compat/blue_skies/cherry_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/blue_skies/stripped_cherry_log.json
  src/generated/resources/data/create/recipes/cutting/compat/blue_skies/stripped_cherry_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/byg/cherry_log.json
  src/generated/resources/data/create/recipes/cutting/compat/byg/cherry_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/byg/stripped_cherry_log.json
  src/generated/resources/data/create/recipes/cutting/compat/byg/stripped_cherry_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/forbidden_arcanus/cherrywood.json
  src/generated/resources/data/create/recipes/cutting/compat/forbidden_arcanus/cherrywood_log.json
  src/generated/resources/data/create/recipes/cutting/compat/forbidden_arcanus/stripped_cherrywood.json
  src/generated/resources/data/create/recipes/cutting/compat/forbidden_arcanus/stripped_cherrywood_log.json
  src/generated/resources/data/create/tags/items/modded_stripped_logs.json
  src/generated/resources/data/create/tags/items/modded_stripped_wood.json
  src/main/java/com/simibubi/create/foundation/data/recipe/CuttingRecipeGen.java
  src/main/java/com/simibubi/create/infrastructure/data/CreateRegistrateTags.java
Labels: area: compatibility, pr type: fix, pr flag: simple

#6801 Fix schematic renderers not correctly being invalidated on resource reloads
  src/main/java/com/simibubi/create/content/schematics/client/SchematicHandler.java
Labels: pr type: fix, pr flag: simple

#6812 Deployer interactions -> Fix to issue #3382
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerMovementBehaviour.java
Labels: pr type: fix, pr flag: simple

#6813 Fix to issue #6784, with schematic renderers not deactivating
  src/main/java/com/simibubi/create/content/schematics/client/SchematicHandler.java
Labels: pr type: fix, pr flag: simple

#6822 Fix Graphics Mode Debug Information
  src/main/java/com/simibubi/create/infrastructure/debugInfo/DebugInformation.java
Labels: pr type: fix, pr flag: simple
