Repository Creators-of-Create/Create, pull requests merged in 2024-03, with the labels that each got.

#5707 Memory leak in CapManipulationBehaviourBase
  src/main/java/com/simibubi/create/foundation/blockEntity/behaviour/inventory/CapManipulationBehaviourBase.java
  src/main/java/com/simibubi/create/foundation/utility/HashableNonNullConsumer.java
Labels: pr type: fix, pr flag: simple

#5772 feat: Make "A New Gauge" Advancement check for AllItemTags#TRACKS
  src/generated/resources/.cache/cache
  src/generated/resources/data/create/advancements/track_0.json
  src/generated/resources/data/create/tags/items/tracks.json
  src/main/java/com/simibubi/create/AllBlocks.java
  src/main/java/com/simibubi/create/AllTags.java
  src/main/java/com/simibubi/create/foundation/advancement/AllAdvancements.java
Labels: pr type: fix, pr flag: simple

#5826 fix: Signal Group NPE
  src/main/java/com/simibubi/create/content/trains/graph/EdgeData.java
  src/main/java/com/simibubi/create/content/trains/graph/TrackGraph.java
Labels: pr type: fix, pr flag: simple

#6227 Fix chromatic compound not working under y0
  src/main/java/com/simibubi/create/content/legacy/ChromaticCompoundItem.java
Labels: pr type: fix, pr flag: simple

#5916 Add & implement spout & clipboard sfx
  src/generated/resources/.cache/cache
  src/generated/resources/assets/create/lang/en_ud.json
  src/generated/resources/assets/create/lang/en_us.json
  src/generated/resources/assets/create/sounds.json
  src/main/java/com/simibubi/create/AllSoundEvents.java
  src/main/java/com/simibubi/create/content/equipment/clipboard/ClipboardScreen.java
  src/main/java/com/simibubi/create/content/fluids/spout/SpoutBlockEntity.java
  src/main/resources/assets/create/sounds/clipboard_check.ogg
  src/main/resources/assets/create/sounds/clipboard_erase.ogg
  src/main/resources/assets/create/sounds/spout.ogg
  src/main/resources/assets/create/sounds/spout_1.ogg
  src/main/resources/assets/create/sounds/spout_2.ogg
  src/main/resources/assets/create/sounds/spout_3.ogg
Labels: pr type: feature

#5941 small change: add Create's icon to .idea for intellij users
  .idea/icon.png
Labels: pr type: feature, pr flag: simple

#5999 Fix #5998, Configs with the same key
  src/main/java/com/simibubi/create/infrastructure/config/CSchematics.java
Labels: pr type: fix, pr flag: simple

#6187 Big Outlines API
  src/main/java/com/simibubi/create/content/decoration/slidingDoor/SlidingDoorBlock.java
  src/main/java/com/simibubi/create/content/trains/track/TrackBlock.java
  src/main/java/com/simibubi/create/foundation/block/BigOutlines.java
  src/main/java/com/simibubi/create/foundation/block/IHaveBigOutline.java
Labels: area: api, pr type: feature, pr flag: simple

#6171 Allow vertical gearboxes to be crafted without crafting a normal gearbox
  src/generated/resources/.cache/cache
  src/generated/resources/data/create/advancements/recipes/create.base/crafting/kinetics/vertical_gearbox.json
  src/generated/resources/data/create/recipes/crafting/kinetics/vertical_gearbox.json
  src/main/java/com/simibubi/create/foundation/data/recipe/StandardRecipeGen.java
Labels: pr type: feature

#6072 Fix deployer anti agro not working, and switch away from deprecated event
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerFakePlayer.java
Labels: pr type: fix, pr flag: simple

#5900 feat: Allow changing the goggle overlay tooltip icon
  src/main/java/com/simibubi/create/content/equipment/goggles/GoggleOverlayRenderer.java
  src/main/java/com/simibubi/create/content/equipment/goggles/IHaveGoggleInformation.java
Labels: area: api, pr type: feature, pr flag: simple

#6158 Increase shape variation in layered/striated ore features
  src/main/java/com/simibubi/create/infrastructure/worldgen/LayeredOreFeature.java
Labels: pr type: feature

#5821 feat: Track Placement breaks flowers
  src/main/java/com/simibubi/create/content/trains/track/TrackPlacement.java
Labels: pr type: feature, pr flag: simple

#6273 Fix changing bogey style not updating the block properly
  src/main/java/com/simibubi/create/content/trains/bogey/AbstractBogeyBlock.java
Labels: pr type: fix, pr flag: simple

#6267 Fix Copycat step placement helper
  src/main/java/com/simibubi/create/content/decoration/copycat/CopycatStepBlock.java
Labels: pr type: fix, pr flag: simple

#6231 Respect 'eternal' modifier from Forbidden and Arcanus in Deployer Recipes
  build.gradle
  src/main/java/com/simibubi/create/content/kinetics/deployer/BeltDeployerCallbacks.java
Labels: area: compatibility, pr type: fix, pr flag: simple

#6224 Add null-safety check on usage of BlockEntity.loadStatic
  src/main/java/com/simibubi/create/foundation/utility/BlockHelper.java
Labels: pr type: fix, pr flag: simple

#5830 fix: Schematics request wrong blocks
  src/main/java/com/simibubi/create/content/schematics/requirement/ItemRequirement.java
Labels: pr type: fix, pr flag: simple
