Repository Creators-of-Create/Create, pull requests merged in 2024-07, with the labels that each got.

#6674 Preserving BakedModel and switching to ItemRenderer.render instead of ItemRenderer.renderStatic
  src/main/java/com/simibubi/create/content/decoration/placard/PlacardRenderer.java
  src/main/java/com/simibubi/create/content/fluids/drain/ItemDrainRenderer.java
  src/main/java/com/simibubi/create/content/kinetics/belt/BeltRenderer.java
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerRenderer.java
  src/main/java/com/simibubi/create/content/kinetics/mechanicalArm/ArmRenderer.java
  src/main/java/com/simibubi/create/content/kinetics/saw/SawRenderer.java
  src/main/java/com/simibubi/create/content/logistics/depot/DepotRenderer.java
Labels: area: rendering, pr type: feature

#6677 Culling Items on belts
  src/main/java/com/simibubi/create/content/kinetics/belt/BeltRenderer.java
  src/main/java/com/simibubi/create/foundation/blockEntity/renderer/SafeBlockEntityRenderer.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: pr type: feature

#6673 Fix schematic visual not disappearing
  src/main/java/com/simibubi/create/content/schematics/client/SchematicHandler.java
Labels: pr type: fix, pr flag: simple

#6664 Encasing blocks plays a placing sound
  src/main/java/com/simibubi/create/content/decoration/encasing/EncasableBlock.java
Labels: pr type: feature, pr flag: simple

#6662 Make Backtank preserve NBT on placement.
  src/generated/resources/.cache/cache
  src/generated/resources/data/create/loot_tables/blocks/copper_backtank.json
  src/generated/resources/data/create/loot_tables/blocks/netherite_backtank.json
  src/generated/resources/data/create/recipes/emptying/compat/alexsmobs/lava_bottle.json
  src/main/java/com/simibubi/create/content/equipment/armor/BacktankBlock.java
  src/main/java/com/simibubi/create/content/equipment/armor/BacktankBlockEntity.java
  src/main/java/com/simibubi/create/foundation/data/BuilderTransformers.java
Labels: pr type: fix

#6507 Total Ram info inside DebugInfo command
  src/main/java/com/simibubi/create/infrastructure/debugInfo/DebugInformation.java
Labels: pr flag: simple

#6595 Remove unnecessary glue ticking
  src/main/java/com/simibubi/create/content/contraptions/glue/SuperGlueEntity.java
Labels: pr flag: simple

#6592 Fix Stabilized contraption offset and incorrect rotation
  src/main/java/com/simibubi/create/content/contraptions/AbstractContraptionEntity.java
  src/main/java/com/simibubi/create/content/contraptions/OrientedContraptionEntity.java
  src/main/java/com/simibubi/create/foundation/utility/AngleHelper.java
Labels: pr type: fix, pr flag: simple

#6477 Goggle Tooltip code cleanup and ModernUI compat
  build.gradle
  src/main/java/com/simibubi/create/compat/Mods.java
  src/main/java/com/simibubi/create/content/contraptions/IDisplayAssemblyExceptions.java
  src/main/java/com/simibubi/create/content/contraptions/elevator/ElevatorContactEditPacket.java
  src/main/java/com/simibubi/create/content/decoration/steamWhistle/WhistleBlockEntity.java
  src/main/java/com/simibubi/create/content/equipment/goggles/GoggleOverlayRenderer.java
  src/main/java/com/simibubi/create/content/fluids/tank/BoilerData.java
  src/main/java/com/simibubi/create/content/kinetics/gauge/GaugeBlockEntity.java
  src/main/java/com/simibubi/create/content/logistics/tunnel/BrassTunnelBlockEntity.java
  src/main/java/com/simibubi/create/content/redstone/analogLever/AnalogLeverBlockEntity.java
  src/main/java/com/simibubi/create/foundation/item/TooltipHelper.java
  src/main/java/com/simibubi/create/foundation/mixin/accessor/MouseHandlerAccessor.java
  src/main/java/com/simibubi/create/foundation/utility/LangBuilder.java
  src/main/resources/create.mixins.json
Labels: pr type: fix

#6542 Fix #6245 : Display links not writing to signs
  src/main/java/com/simibubi/create/content/redstone/displayLink/target/SignDisplayTarget.java
Labels: pr type: fix, pr flag: simple

#6482 Fence Gates on Trains
  src/main/java/com/simibubi/create/AllInteractionBehaviours.java
  src/main/java/com/simibubi/create/content/contraptions/behaviour/FenceGateMovingInteraction.java
Labels: pr type: feature, pr flag: simple

#6468 Fix Ore Crushing Inconsistency and add Gilded Blackstone Crushing
  src/generated/resources/.cache/cache
  src/generated/resources/data/create/recipes/crushing/deepslate_coal_ore.json
  src/generated/resources/data/create/recipes/crushing/gilded_blackstone.json
  src/main/java/com/simibubi/create/foundation/data/recipe/CrushingRecipeGen.java
Labels: pr type: fix, pr flag: simple

#6467 Fix dupe bug with using a wrench in claimed chunks
  build.gradle
  src/main/java/com/simibubi/create/content/equipment/wrench/IWrenchable.java
Labels: pr type: fix, pr flag: simple

#6464 Allow any fire resistant armor to be used in lava diving
  src/main/java/com/simibubi/create/content/equipment/armor/NetheriteDivingHandler.java
Labels: pr type: fix, pr flag: simple

#6461 Fix Large Water Wheel Structural blocks catching on fire
  src/main/java/com/simibubi/create/content/kinetics/waterwheel/WaterWheelStructuralBlock.java
Labels: pr type: fix, pr flag: simple

#6460 Fix NPE caused by empty lectern controller in a debug world
  src/main/java/com/simibubi/create/content/redstone/link/controller/LecternControllerBlockEntity.java
Labels: pr type: fix, pr flag: simple

#6458 Fix Honey Buckets & Chocolate Buckets not showing up in creative tabs
  src/main/java/com/simibubi/create/AllFluids.java
Labels: pr type: fix, pr flag: simple

#6446 Fix contraption step sounds
  src/main/java/com/simibubi/create/foundation/mixin/client/EntityContraptionInteractionMixin.java
Labels: pr type: fix, pr flag: simple

#6427 Fix concurrency issue in Creative Tabs System
  src/main/java/com/simibubi/create/foundation/data/CreateRegistrate.java
Labels: pr type: fix, pr flag: simple

#6424 Fix Deployer Recipe Error Messages
  src/main/java/com/simibubi/create/content/kinetics/deployer/ItemApplicationRecipe.java
Labels: pr type: fix, pr flag: simple

#6406 Fix Filters not Respecting 'Respect Data' option
  src/main/java/com/simibubi/create/content/logistics/filter/FilterItemStack.java
Labels: pr type: fix, pr flag: simple

#6386 Allow Ponder to be re-bound
  src/generated/resources/.cache/cache
  src/generated/resources/assets/create/lang/en_ud.json
  src/generated/resources/assets/create/lang/en_us.json
  src/main/java/com/simibubi/create/AllKeys.java
  src/main/java/com/simibubi/create/foundation/ponder/PonderTooltipHandler.java
  src/main/resources/assets/create/lang/default/interface.json
Labels: pr type: feature, pr flag: simple

#6385 Respect Manual Only Recipes
  src/main/java/com/simibubi/create/compat/jei/CreateJEI.java
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerBlockEntity.java
  src/main/java/com/simibubi/create/content/kinetics/fan/processing/AllFanProcessingTypes.java
Labels: pr type: fix

#6356 Fix IHaveBigOutline not working in the y axis
  src/main/java/com/simibubi/create/foundation/block/BigOutlines.java
Labels: pr type: fix, pr flag: simple

#6352 Minor ClipboardCloneable outline renderer oversight
  src/main/java/com/simibubi/create/content/equipment/clipboard/ClipboardValueSettingsHandler.java
Labels: pr type: fix, pr flag: simple

#6343 General code cleanup and small fixes
  src/generated/resources/.cache/cache
  src/generated/resources/data/create/tags/blocks/brittle.json
  src/generated/resources/data/create/tags/blocks/corals.json
  src/generated/resources/data/create/tags/blocks/movable_empty_collider.json
  src/main/java/com/simibubi/create/AllTags.java
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerFakePlayer.java
  src/main/java/com/simibubi/create/infrastructure/data/CreateRegistrateTags.java
Labels: pr type: fix, pr flag: simple

#6325 Null protection & Readability changes
  src/main/java/com/simibubi/create/content/trains/entity/Train.java
  src/main/java/com/simibubi/create/content/trains/entity/TravellingPoint.java
Labels: pr type: fix

#6285 Versioned Inventories for funnel input
  src/main/java/com/simibubi/create/content/kinetics/belt/BeltBlockEntity.java
  src/main/java/com/simibubi/create/content/kinetics/belt/transport/BeltFunnelInteractionHandler.java
Labels: pr type: fix, pr flag: simple

#6281 Add Ice Compacting Recipe and runData
  src/generated/resources/.cache/cache
  src/generated/resources/data/create/recipes/compacting/ice.json
  src/generated/resources/data/create/recipes/emptying/compat/alexsmobs/lava_bottle.json
  src/main/java/com/simibubi/create/foundation/data/recipe/CompactingRecipeGen.java
Labels: pr type: feature, pr flag: simple

#6145 restore the invariant that draining is the inverse of filling (bug #5921)
  src/main/java/com/simibubi/create/content/fluids/transfer/FluidManipulationBehaviour.java
Labels: pr type: fix

#6110 Implemented roots block tag for tree cutting
  src/generated/resources/.cache/2d64935085b86659cb7857bad9701dbf9bab6e4c
  src/generated/resources/data/create/tags/blocks/roots.json
  src/main/java/com/simibubi/create/AllTags.java
  src/main/java/com/simibubi/create/foundation/utility/TreeCutter.java
  src/main/java/com/simibubi/create/infrastructure/data/CreateRegistrateTags.java
Labels: area: compatibility, pr type: fix

#6088 Added station blockstate check
  src/main/java/com/simibubi/create/content/trains/station/StationBlockEntity.java
Labels: pr type: fix

#6065 Added missing whitespace to TranslatingContraption.java
  src/main/java/com/simibubi/create/content/contraptions/TranslatingContraption.java
Labels: pr flag: simple

#6062 Fix #4880 Dropper Dupe
  src/main/java/com/simibubi/create/content/contraptions/behaviour/dispenser/DropperMovementBehaviour.java
Labels: pr type: fix, pr flag: simple

#5871 Fixed Potato Cannon Shooter Credit
  src/main/java/com/simibubi/create/content/equipment/potatoCannon/PotatoProjectileEntity.java
Labels: pr type: fix, pr flag: simple

#5866 Fix Automated Brewing of Modded Potions
  src/main/java/com/simibubi/create/content/fluids/potion/PotionMixingRecipes.java
Labels: area: compatibility, pr type: fix, pr flag: simple
