Repository Creators-of-Create/Create, pull requests merged in 2025-01, with the labels that each got.

#7040 Fix Mechanical Arm interactions with Jukeboxes
  src/main/java/com/simibubi/create/content/kinetics/mechanicalArm/AllArmInteractionPointTypes.java
Labels: pr type: fix, pr flag: simple

#6978 Fix toolboxes not giving a comparator output signal
  src/main/java/com/simibubi/create/content/equipment/toolbox/ToolboxBlock.java
  src/main/java/com/simibubi/create/content/logistics/vault/ItemVaultBlock.java
  src/main/java/com/simibubi/create/foundation/item/ItemHelper.java
Labels: pr type: fix, pr flag: simple

#7078 Sync AllPortalTracks with Create Fabric
  src/main/java/com/simibubi/create/compat/Mods.java
  src/main/java/com/simibubi/create/compat/betterend/BetterEndPortalCompat.java
  src/main/java/com/simibubi/create/content/trains/track/AllPortalTracks.java
Labels: pr type: feature, pr flag: simple

#7053 Add CopperBlockSet slabs and stairs to correct tags
  src/generated/resources/.cache/2d64935085b86659cb7857bad9701dbf9bab6e4c
  src/generated/resources/data/minecraft/tags/blocks/slabs.json
  src/generated/resources/data/minecraft/tags/blocks/stairs.json
  src/main/java/com/simibubi/create/foundation/block/CopperBlockSet.java
Labels: pr type: fix, pr flag: simple

#7127 Fix copycat panels showing faces when using sodium
  src/main/java/com/simibubi/create/content/decoration/copycat/CopycatPanelBlock.java
Labels: pr type: fix, pr flag: simple

#7126 Fix waterlogged bracketed kinetics dropping the bracket
  src/main/java/com/simibubi/create/content/kinetics/simpleRelays/AbstractSimpleShaftBlock.java
Labels: pr type: fix, pr flag: simple

#7112 Switch away from using streams in ContraptionCollider
  src/main/java/com/simibubi/create/content/contraptions/ContraptionCollider.java
Labels: pr type: fix, pr flag: simple

#7054 Fix fluids not being placed into flowing fluids of the same type
  src/main/java/com/simibubi/create/content/fluids/OpenEndedPipe.java
Labels: pr type: fix, pr flag: simple

#7058 Fix schematicannons not consuming right amount of specific items
  src/main/java/com/simibubi/create/foundation/utility/BlockHelper.java
Labels: pr type: fix, pr flag: simple

#7057 Fix backtanks getting incompatible enchants via smithing tables
  build.gradle
  src/main/java/com/simibubi/create/foundation/mixin/SmithingMenuMixin.java
  src/main/resources/create.mixins.json
Labels: pr type: fix, pr flag: simple

#7150 Fix Lectern Controllers storing ItemStacks from nbt
  src/main/java/com/simibubi/create/content/redstone/link/controller/LecternControllerBlockEntity.java
Labels: pr type: fix, pr flag: simple

#7274 Optimize spout recipe generation by avoiding filling non-empty items
  src/main/java/com/simibubi/create/compat/jei/category/SpoutCategory.java
Labels: pr flag: simple

#7265 Add DyeHelper api
  src/main/java/com/simibubi/create/content/contraptions/actors/contraptionControls/ContraptionControlsBlockEntity.java
  src/main/java/com/simibubi/create/content/contraptions/actors/contraptionControls/ContraptionControlsRenderer.java
  src/main/java/com/simibubi/create/content/redstone/nixieTube/NixieTubeRenderer.java
  src/main/java/com/simibubi/create/content/trains/display/FlapDisplayBlockEntity.java
  src/main/java/com/simibubi/create/foundation/utility/DyeHelper.java
  src/main/java/com/simibubi/create/infrastructure/debugInfo/ServerDebugInfoPacket.java
Labels: area: compatibility, area: api, pr type: fix

#7216 Fix enchantments getting trimmed from non-filter items
  src/main/java/com/simibubi/create/content/logistics/filter/FilterItemStack.java
Labels: pr type: fix, pr flag: simple

#7259 Allow sandpaper to be used in deploying recipe
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerBlockEntity.java
Labels: pr type: fix, pr flag: simple

#7038 mechanical drill/saw uses block soundsource
  src/main/java/com/simibubi/create/content/kinetics/base/BlockBreakingKineticBlockEntity.java
Labels: pr type: fix, pr flag: simple

#7059 Fix getSize() erroring on newly loaded display link peripherals
  src/main/java/com/simibubi/create/compat/computercraft/implementation/peripherals/DisplayLinkPeripheral.java
Labels: pr type: fix, pr flag: simple

#7263 Sugar Cane Variants tag
  src/generated/resources/.cache/2d64935085b86659cb7857bad9701dbf9bab6e4c
  src/generated/resources/data/create/tags/blocks/sugar_cane_variants.json
  src/main/java/com/simibubi/create/AllTags.java
  src/main/java/com/simibubi/create/content/contraptions/actors/harvester/HarvesterMovementBehaviour.java
  src/main/java/com/simibubi/create/infrastructure/data/CreateRegistrateTags.java
Labels: area: compatibility, area: api, pr flag: simple

#7186 Add pressing recipes for coarse_dirt->dirt_path and rooted_dirt->dirt_path
  src/generated/resources/data/create/recipes/pressing/path.json
  src/main/java/com/simibubi/create/foundation/data/recipe/PressingRecipeGen.java
Labels: pr type: fix, pr flag: simple

#6934 Update JEI integration and add potion fluids to the ingredient list
  gradle.properties
  src/main/java/com/simibubi/create/AllFluids.java
  src/main/java/com/simibubi/create/compat/jei/CreateJEI.java
  src/main/java/com/simibubi/create/compat/jei/category/BasinCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/CreateRecipeCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/CrushingCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/DeployingCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/ItemApplicationCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/ItemDrainCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/MillingCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/PolishingCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/PressingCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/ProcessingViaFanCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/SawingCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/SpoutCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/sequencedAssembly/SequencedAssemblySubCategory.java
  src/main/java/com/simibubi/create/content/fluids/VirtualFluid.java
  src/main/java/com/simibubi/create/content/fluids/potion/PotionFluid.java
  src/main/java/com/simibubi/create/content/fluids/potion/PotionFluidHandler.java
  src/main/java/com/simibubi/create/foundation/data/CreateRegistrate.java
  src/main/java/com/simibubi/create/foundation/data/VirtualFluidBuilder.java
  src/main/resources/META-INF/mods.toml
Labels: pr type: fix, pr type: feature

#7025 fix spout weird rendering and rare client crash
  src/main/java/com/simibubi/create/content/fluids/spout/SpoutBlockEntity.java
  src/main/java/com/simibubi/create/content/fluids/spout/SpoutRenderer.java
Labels: pr type: fix, pr flag: simple

#7030 Add api to add custom conductors to trains
  src/main/java/com/simibubi/create/AllBlocks.java
  src/main/java/com/simibubi/create/api/contraption/train/TrainConductorHandler.java
  src/main/java/com/simibubi/create/content/processing/burner/BlockBasedTrainConductorInteractionBehaviour.java
  src/main/java/com/simibubi/create/content/trains/entity/CarriageContraption.java
  src/main/java/com/simibubi/create/content/trains/entity/CarriageContraptionEntity.java
Labels: area: api
