Repository Creators-of-Create/Create, pull requests merged in 2025-03, with the labels that each got.

#7649 Custom Unpacking API
  src/main/java/com/simibubi/create/Create.java
  src/main/java/com/simibubi/create/api/unpacking/UnpackingHandler.java
  src/main/java/com/simibubi/create/api/unpacking/VoidingUnpackingHandler.java
  src/main/java/com/simibubi/create/content/equipment/blueprint/BlueprintOverlayRenderer.java
  src/main/java/com/simibubi/create/content/kinetics/crafter/ConnectedInputHandler.java
  src/main/java/com/simibubi/create/content/kinetics/crafter/MechanicalCrafterBlockEntity.java
  src/main/java/com/simibubi/create/content/logistics/packager/AllUnpackingHandlers.java
  src/main/java/com/simibubi/create/content/logistics/packager/PackagerBlockEntity.java
  src/main/java/com/simibubi/create/foundation/item/ItemHelper.java
  src/main/java/com/simibubi/create/impl/unpacking/BasinUnpackingHandler.java
  src/main/java/com/simibubi/create/impl/unpacking/CrafterUnpackingHandler.java
  src/main/java/com/simibubi/create/impl/unpacking/DefaultUnpackingHandler.java
Labels: area: api, pr type: feature

#7660 Improve RuntimeDataGenerator and re-add some variant logs
  src/generated/resources/.cache/2d64935085b86659cb7857bad9701dbf9bab6e4c
  src/generated/resources/.cache/b256105d8411632b0d585496ea8944a751a08034
  src/generated/resources/data/create/recipes/cutting/bamboo_block.json
  src/generated/resources/data/create/recipes/cutting/compat/ars_elemental/stripped_yellow_archwood.json
  src/generated/resources/data/create/recipes/cutting/compat/ars_elemental/stripped_yellow_archwood_log.json
  src/generated/resources/data/create/recipes/cutting/compat/autumnity/sappy_maple_log.json
  src/generated/resources/data/create/recipes/cutting/compat/autumnity/sappy_maple_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/endergetic/glowing_poise_stem.json
  src/generated/resources/data/create/recipes/cutting/compat/endergetic/glowing_poise_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/regions_unexplored/ashen_log.json
  src/generated/resources/data/create/recipes/cutting/compat/regions_unexplored/ashen_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/regions_unexplored/brimwood_log_magma.json
  src/generated/resources/data/create/recipes/cutting/stripped_bamboo_block.json
  src/generated/resources/data/create/tags/items/modded_stripped_logs.json
  src/generated/resources/data/create/tags/items/modded_stripped_wood.json
  src/main/java/com/simibubi/create/foundation/data/RuntimeDataGenerator.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CuttingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/Mods.java
  src/main/java/com/simibubi/create/infrastructure/data/CreateRegistrateTags.java
Labels: pr type: feature

#7597 Fix: Rotate Menu Keybind not supporting mouse buttons
  src/main/java/com/simibubi/create/foundation/events/InputEvents.java
Labels: pr type: fix, pr flag: simple

#7610 Fixed positioning when attaching to chain conveyer not respecting player's scale attribute
  src/main/java/com/simibubi/create/content/kinetics/chainConveyor/ChainConveyorRidingHandler.java
Labels: pr type: fix, pr flag: simple

#7745 Fix #7691: No longer being transported when only wearing cardboard boots
  src/main/java/com/simibubi/create/content/kinetics/belt/transport/BeltMovementHandler.java
Labels: pr type: fix, pr flag: simple

#7832 Update BogeyBlockEntityVisual.java | Fixed bogey lighting not updatin…
  src/main/java/com/simibubi/create/content/trains/bogey/BogeyBlockEntityVisual.java
Labels: area: rendering, pr type: fix, pr flag: simple

#7862 Fix addons running Create's datagen
  gradle.properties
  src/main/java/com/simibubi/create/infrastructure/data/CreateDatagen.java
Labels: pr type: fix, pr flag: simple

#7822 change sandpaper item render type
  src/main/java/com/simibubi/create/content/equipment/sandPaper/SandPaperItemRenderer.java
Labels: pr type: fix, pr flag: simple

#7977 Fix goggles not swapping with helmet
  src/main/java/com/simibubi/create/content/equipment/goggles/GogglesItem.java
Labels: pr type: fix, pr flag: simple

#8105 [1.21.1] Fix Processing Output not applying data components
  src/main/java/com/simibubi/create/content/processing/recipe/ProcessingOutput.java
Labels: pr type: fix, pr flag: simple
