Repository Creators-of-Create/Create, pull requests merged in 2025-09, with the labels that each got.

#9050 Fix edge case where runtimedatagen creates cutting recipes with empty ingredients
  src/generated/resources/.cache/5971ca79ecd127e7d1e65be1cd906ac939e6a245
  src/generated/resources/.cache/b256105d8411632b0d585496ea8944a751a08034
  src/generated/resources/data/create/recipes/cutting/compat/netherexp/cerebrage_claret_hyphae.json
  src/generated/resources/data/create/recipes/cutting/compat/netherexp/cerebrage_claret_stem.json
  src/generated/resources/data/create/tags/items/not_upright_on_belt.json
  src/main/java/com/simibubi/create/foundation/data/RuntimeDataGenerator.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateCuttingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/Mods.java
Labels: pr type: fix, pr flag: simple

#8813 fix: Incorrect flower class for harvester
  src/main/java/com/simibubi/create/content/contraptions/actors/harvester/HarvesterMovementBehaviour.java
Labels: pr type: fix, pr flag: simple

#8073 Fix curved track targeting at high track max placement length
  src/main/java/com/simibubi/create/content/trains/track/CurvedTrackDestroyPacket.java
  src/main/java/com/simibubi/create/content/trains/track/CurvedTrackSelectionPacket.java
  src/main/java/com/simibubi/create/content/trains/track/TrackTargetingBlockItem.java
Labels: pr type: fix, pr flag: simple

#9033 Fix fan blasting not respecting manual only blasting recipes
  src/main/java/com/simibubi/create/content/kinetics/fan/processing/AllFanProcessingTypes.java
Labels: pr type: fix, pr flag: simple

#8932 Fix for #8918
  src/main/java/com/simibubi/create/content/kinetics/crafter/MechanicalCrafterBlockEntity.java
Labels: pr type: fix, pr flag: simple

#8919 Fix for #8916
  src/main/java/com/simibubi/create/foundation/recipe/ItemCopyingRecipe.java
Labels: pr type: fix, pr flag: simple

#8386 Waterwheels using Archwood Planks, rendering defaults to Blue Archwood
  src/main/java/com/simibubi/create/content/kinetics/waterwheel/WaterWheelRenderer.java
Labels: pr type: fix, pr flag: simple

#8895 Change compat datagen from enum to interface
  src/main/java/com/simibubi/create/api/data/recipe/CuttingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/DatagenMod.java
  src/main/java/com/simibubi/create/api/data/recipe/FillingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/HauntingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/MixingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/PressingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/WashingRecipeGen.java
  src/main/java/com/simibubi/create/content/processing/recipe/ProcessingRecipeBuilder.java
  src/main/java/com/simibubi/create/foundation/data/SimpleDatagenIngredient.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateCompactingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateCuttingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateDeployingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateEmptyingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateFillingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateHauntingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateItemApplicationRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateMechanicalCraftingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateMixingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreatePolishingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreatePressingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateSequencedAssemblyRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateWashingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/Mods.java
  src/main/java/com/simibubi/create/infrastructure/data/CreateRegistrateTags.java
Labels: area: api

#9262 Fix max crusher advancement only working for positive speeds.
  src/main/java/com/simibubi/create/content/kinetics/crusher/CrushingWheelControllerBlock.java
Labels: pr type: fix, pr flag: simple

#8080 Cardboard sneaking hotfix
  src/main/java/com/simibubi/create/content/equipment/armor/CardboardArmorHandler.java
Labels: pr type: fix

#9286 fixed empty list filter blacklist bug in FilterItemStack
  src/main/java/com/simibubi/create/content/logistics/filter/FilterItemStack.java
Labels: pr type: fix, pr flag: simple
