Repository Creators-of-Create/Create, pull requests merged in 2025-05, with the labels that each got.

#8429 Tick restockers
  src/main/java/com/simibubi/create/content/logistics/factoryBoard/FactoryPanelBehaviour.java
Labels: pr type: fix, pr flag: simple

#8233 [1.21.1] fix missing maxRange override in ServerboundChainConveyorRidingPacket
  src/main/java/com/simibubi/create/content/kinetics/chainConveyor/ServerboundChainConveyorRidingPacket.java
Labels: pr type: fix, pr flag: simple

#8316 Fix block setting methods of WorldInstructions do not make SmartBlockEntity virtual
  src/main/java/com/simibubi/create/foundation/ponder/CreateSceneBuilder.java
Labels: pr type: fix, pr flag: simple

#8368 [1.21.1] Fix Potato Cannon doesn't playing the proper animation when fired
  src/main/java/com/simibubi/create/content/equipment/potatoCannon/PotatoCannonItem.java
Labels: pr type: fix, pr flag: simple

#8351 Fix recipe IDs not showing in JEI
  src/main/java/com/simibubi/create/compat/jei/CreateJEI.java
  src/main/java/com/simibubi/create/compat/jei/category/CreateRecipeCategory.java
Labels: pr type: fix, pr flag: simple

#8507 Fix Station Peripheral setSchedule verification logic
  src/main/java/com/simibubi/create/compat/computercraft/implementation/peripherals/StationPeripheral.java
  src/main/java/com/simibubi/create/content/trains/schedule/ScheduleRuntime.java
Labels: pr type: fix, pr flag: simple

#8282 Extend the width of background texture of scroll value setting lable
  src/main/java/com/simibubi/create/foundation/gui/AllGuiTextures.java
  src/main/resources/assets/create/textures/gui/value_settings.png
Labels: pr type: fix, pr flag: simple

#8313 add invisible output slots every loop for each step's secondary outputs
  src/main/java/com/simibubi/create/compat/jei/category/SequencedAssemblyCategory.java
Labels: pr type: fix, pr flag: simple

#8323 Fix crash with null level during world gen (from third party mods)
  src/main/java/com/simibubi/create/content/logistics/tunnel/BeltTunnelBlockEntity.java
Labels: pr type: fix, pr flag: simple

#8335 Fix item duplication on belts
  src/main/java/com/simibubi/create/content/kinetics/belt/transport/BeltCrusherInteractionHandler.java
  src/main/java/com/simibubi/create/content/kinetics/belt/transport/BeltFunnelInteractionHandler.java
  src/main/java/com/simibubi/create/content/kinetics/belt/transport/BeltInventory.java
  src/main/java/com/simibubi/create/content/kinetics/belt/transport/BeltTunnelInteractionHandler.java
Labels: pr type: fix, pr flag: simple

#8173 TransformableBlockEntity implementation for DisplayLinkBlockEntity
  src/main/java/com/simibubi/create/content/redstone/displayLink/DisplayLinkBlockEntity.java
Labels: pr type: fix, pr flag: simple

#8428 Send edge points in the same packet as their edges
  src/main/java/com/simibubi/create/content/trains/graph/TrackGraphSync.java
Labels: pr type: fix, pr flag: simple

#8435 Fix belt connector consumption when not having enough shafts to split the belt
  src/main/java/com/simibubi/create/content/kinetics/belt/BeltSlicer.java
Labels: pr type: fix, pr flag: simple

#8318 [1.21.1] Fix outdated data format of BlockEntity of certain ponder files
  src/main/resources/assets/create/ponder/fluid_valve.nbt
  src/main/resources/assets/create/ponder/mechanical_pump/flow.nbt
  src/main/resources/assets/create/ponder/mechanical_pump/speed.nbt
Labels: pr type: fix, pr flag: simple

#8520 Fix Self-Driving Cart achievement being very obtuse to obtain
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerHandler.java
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerMovementBehaviour.java
Labels: pr type: fix, pr flag: simple

#8514 Allow addons to use serializer codec by using interface instead of enum
  src/main/java/com/simibubi/create/content/processing/recipe/ProcessingRecipeSerializer.java
Labels: area: api

#7945 [1.21.1] Processing Recipe Rework
  src/main/java/com/simibubi/create/AllRecipeTypes.java
  src/main/java/com/simibubi/create/api/data/recipe/BaseRecipeProvider.java
  src/main/java/com/simibubi/create/api/data/recipe/CompactingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/CrushingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/CuttingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/DeployingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/EmptyingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/FillingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/HauntingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/ItemApplicationRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/MillingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/MixingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/PolishingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/PressingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/ProcessingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/StandardProcessingRecipeGen.java
  src/main/java/com/simibubi/create/api/data/recipe/WashingRecipeGen.java
  src/main/java/com/simibubi/create/compat/jei/ConversionRecipe.java
  src/main/java/com/simibubi/create/compat/jei/CreateJEI.java
  src/main/java/com/simibubi/create/compat/jei/category/CreateRecipeCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/CrushingCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/ItemDrainCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/ProcessingViaFanCategory.java
  src/main/java/com/simibubi/create/compat/jei/category/SpoutCategory.java
  src/main/java/com/simibubi/create/content/equipment/sandPaper/SandPaperPolishingRecipe.java
  src/main/java/com/simibubi/create/content/fluids/potion/PotionMixingRecipes.java
  src/main/java/com/simibubi/create/content/fluids/transfer/EmptyingRecipe.java
  src/main/java/com/simibubi/create/content/fluids/transfer/FillingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/crusher/AbstractCrushingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/crusher/CrushingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/crusher/CrushingWheelControllerBlockEntity.java
  src/main/java/com/simibubi/create/content/kinetics/deployer/DeployerApplicationRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/deployer/ItemApplicationRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/deployer/ItemApplicationRecipeParams.java
  src/main/java/com/simibubi/create/content/kinetics/deployer/ManualApplicationRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/fan/processing/HauntingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/fan/processing/SplashingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/millstone/MillingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/mixer/CompactingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/mixer/MechanicalMixerBlockEntity.java
  src/main/java/com/simibubi/create/content/kinetics/mixer/MixingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/press/PressingRecipe.java
  src/main/java/com/simibubi/create/content/kinetics/saw/CuttingRecipe.java
  src/main/java/com/simibubi/create/content/processing/basin/BasinRecipe.java
  src/main/java/com/simibubi/create/content/processing/recipe/ProcessingRecipe.java
  src/main/java/com/simibubi/create/content/processing/recipe/ProcessingRecipeBuilder.java
  src/main/java/com/simibubi/create/content/processing/recipe/ProcessingRecipeParams.java
  src/main/java/com/simibubi/create/content/processing/recipe/ProcessingRecipeSerializer.java
  src/main/java/com/simibubi/create/content/processing/recipe/StandardProcessingRecipe.java
  src/main/java/com/simibubi/create/content/processing/sequenced/SequencedAssemblyRecipe.java
  src/main/java/com/simibubi/create/content/processing/sequenced/SequencedAssemblyRecipeBuilder.java
  src/main/java/com/simibubi/create/content/processing/sequenced/SequencedRecipe.java
  src/main/java/com/simibubi/create/foundation/data/RuntimeDataGenerator.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateCrushingRecipeGen.java
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateRecipeProvider.java
  src/main/java/com/simibubi/create/foundation/data/recipe/LogStrippingFakeRecipes.java
  src/main/java/com/simibubi/create/foundation/recipe/RecipeApplier.java
Labels: area: api, pr type: feature
