Repository Creators-of-Create/Create, pull requests merged in 2025-07, with the labels that each got.

#8859 Fix: cardboard armor checking for explicit items
  src/main/java/com/simibubi/create/content/equipment/armor/CardboardArmorHandler.java
Labels: area: api, pr type: feature

#8947 Fix crushing wheel not checking that other wheel is actually spinning
  src/main/java/com/simibubi/create/content/kinetics/crusher/CrushingWheelBlock.java
Labels: pr type: fix, pr flag: simple

#8845 fix crash when mechanical pump block is placed without player
  src/main/java/com/simibubi/create/content/fluids/pump/PumpBlock.java
Labels: pr type: fix

#8778 Remove Ars Nouveau compat recipes that are already generated at runtime
  src/generated/resources/.cache/b256105d8411632b0d585496ea8944a751a08034
  src/generated/resources/data/create/recipes/cutting/compat/ars_nouveau/green_archwood_log.json
  src/generated/resources/data/create/recipes/cutting/compat/ars_nouveau/green_archwood_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/ars_nouveau/purple_archwood_log.json
  src/generated/resources/data/create/recipes/cutting/compat/ars_nouveau/purple_archwood_wood.json
  src/generated/resources/data/create/recipes/cutting/compat/ars_nouveau/red_archwood_log.json
  src/generated/resources/data/create/recipes/cutting/compat/ars_nouveau/red_archwood_wood.json
  src/main/java/com/simibubi/create/foundation/data/recipe/CreateCuttingRecipeGen.java
Labels: pr type: fix, pr flag: simple
